server:
  port: 8083
spring:
  application:
    name: notificacao-service
  datasource:
    url: jdbc:postgresql://localhost:5432/notificacaoservice
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: seu-email@gmail.com
    password: sua-senha
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notificacao-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
kafka:
  topics:
    boleto-perto-vencimento: boleto-perto-vencimento
    boleto-vencido: boleto-vencido
